name: holy_money
description: Holy money manager

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.9.7+2
  image_picker: ^0.6.0+2
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  firebase_messaging: ^4.0.0+1
  timeago: 2.0.17
  cached_network_image: 2.0.0-rc
  flutter_svg:
  bubble_bottom_bar: ^1.2.0
  pk_skeleton: 
  flutter_vector_icons: ^0.2.1
  masked_text_input_formatter: "0.0.1"
  searchable_dropdown: ^1.1.0
  giffy_dialog: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/google_signin_button.png

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontMed
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MontThin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
